### ISSUE TITLE
Enemy Bubble Encapsulation

### ISSUE THREAD

**Issue by jessetilro** [dalderliesten/Scrumbledore#106]
An enemy shall float in a bubble if it is hit by a bubble and the bubble’s lifetime shall be increased.
Once an enemy encapsulating bubble is hit by the player, it shall be destroyed and drop fruit.
Once an enemy encapsulating bubble’s lifetime is depleted, it shall be destroyed and shall drop the enemy back in the level.
If the player’s fired projectile hits an enemy already floating in the bubble, the enemy in the bubble shall have the time floating in that bubble extended.
<feature

**Comment by FlorisXll** [comment]
Implementation finished. Waiting with making a pull request before NPC collissions have been handled.
