### ISSUE TITLE
Fix Player Collision / Event Handling

### ISSUE THREAD

**Issue by jessetilro** [dalderliesten/Scrumbledore#108]
Fix making horizontal moving while jumping and making collision with walls (stair problem). Fix colliding with wall from bottom and colliding with wall from the side.

The key events should be handled like key holding instead of on key press / release. Based on whether a key is held down or not, player actions are added every step.
<bug

**Comment by NielsWarnars** [comment]
Something goes wrong in the Collision!collidingFromRight() method

**Comment by NielsWarnars** [comment]
On second thought:
The testDetectNPCPlatformFromRight test method is wrong

NPC npc = new NPC(new Vector(33, 0), new Vector(32, 32)); needs to be:
NPC npc = new NPC(new Vector(32, 0), new Vector(32, 32)); 

In the last case the test will fail

**Comment by jessetilro** [comment]
Actually those coordinates do not matter that much given we use a precision offset. The solution is in the following: vertical collision detection HAS to be done in an earlier stage than horizontal. If a horizontal collision is detected before any vertical, the element's vertical component of its speed vector is not set to zero yet, which leads to the element falling inside of the wall below itself during predictive collision detection.
