### ISSUE TITLE
Fix GUI Logger Choices

### ISSUE THREAD

**Issue by dalderliesten** [dalderliesten/Scrumbledore#169]
The logger choices in the updated settings menu only allow one visual choice to be seen (although it works fine behind the scenes).  Check reason and fix this.

**Comment by dalderliesten** [comment]
Just wish to add that the bug had existed in the old GUI, and I managed to fix it then.  I encourage looking at the fix then and see if it applies here, in theory its the same back-end code.  @NielsWarnars

**Comment by NielsWarnars** [comment]
Issue seems to be caused by the css as values are still assigned to buttons correctly

**Comment by dalderliesten** [comment]
Thanks, retaking it.

**Comment by NielsWarnars** [comment]
Without the inclusion of the CSS style sheet all buttons are showing up correctly: https://github.com/dalderliesten/Scrumbledore/blob/release/src/main/java/nl/tudelft/scrumbledore/userinterface/SettingsMenu.java#L52

**Comment by dalderliesten** [comment]
Got it, thanks!

**Comment by dalderliesten** [comment]
Fixed.
