### ISSUE TITLE
Fix elements moving through walls

### ISSUE THREAD

**Issue by dalderliesten** [dalderliesten/Scrumbledore#192]
Projectiles can be shot through walls when hugging them, this is not supposed to happen. A simliar failure occurs with other elements spawned right next to walls.

<bug

**Comment by jessetilro** [comment]
The current collision detection only detects collisions when they are about to happen and when they are happening now (touching within 2 pixel range). Collision that just happened (elements overlapping) should also be recognized.
<bug
