### ISSUE TITLE
Fix being Tarzan and climbing the walls 

### ISSUE THREAD

**Issue by FlorisXll** [dalderliesten/Scrumbledore#213]
Right now you can climb the walls pressing the 'left' and 'up' key at the same time next to a wall.

**Comment by jessetilro** [comment]
I think this is great, why don't we extend this behavior to make it Wall Jumping instead?

**Comment by FlorisXll** [comment]
I think that this might make the game too easy (and perhaps less fun) since we already have a jumping mechanic to get higher  up (bubbles!).

<suggestion

**Comment by jessetilro** [comment]
Agreed

**Comment by dalderliesten** [comment]
Agree with Floris.

**Comment by dalderliesten** [comment]
Going to give this a try.

**Comment by dalderliesten** [comment]
Did not work.  Untagging, need help.
