### ISSUE TITLE
Fix pressing space to activate buttons in the bottom menu

### ISSUE THREAD

**Issue by FlorisXll** [dalderliesten/Scrumbledore#214]
Whenever you press space you use one of the buttons in the bottom menu. This is determined by which button is selected. For instance, if you press tab you select the next button in line.

**Comment by FlorisXll** [comment]
I suggest we make the spacebar inavailable to make sure you don't press any buttons unnecessarily.

**Comment by jessetilro** [comment]
Agreed

**Comment by dalderliesten** [comment]
As explained in the pull request of #240, this fix is as close as we'll come.
