### ISSUE TITLE
Update race condition prevention

### ISSUE THREAD

**Issue by jessetilro** [dalderliesten/Scrumbledore#227]
Update race condition prevention with a more sofisticated solution: method synchronization just like in the Singleton classes for thread safety rather than juggling data structures around.
<organisation

**Comment by NielsWarnars** [comment]
That is not the cause of the issue (as only one Game thread exists). For example: take a look at the BubbleActionsLevelModifier.modify() method. In this method you loop over all bubbles in the level class and at a certain point (bub.getLifetime() <= 0) a bubble is deleted from this list. But as you know you cannot remove an element from a list that you're currently looping through, thus resulting in a Concurrent Modification Exception (race condition).

  for (Bubble bub : level.getBubbles()) {  // <-- Loop here
      if (bub.getLifetime() <= 0) {
...
        level.getBubbles().remove(bub); // <-- Remove element here
      } 
  }

<organisation
